### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by jennazenk**
Please describe the purpose of this pull request below.
The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)

Copy/paste from CHANGELOG.md is good

### Changed
- update README
- Clean up

### CODE REVIEW

**Comment by schmidsi** [comment]
Please fix eslint errors to get a green travis build according to #179

**Comment by jennazenk** [comment]
Remaining eslint errors come for the dangling _eth and also importing schemas that we don't use but we potentially want to reintroduce. On hold until we decide what we want to do with this

**Comment by schmidsi** [comment]
Please fix eslint errors to get a green travis build according to #179

**Comment by jennazenk** [comment]
Intent of that PR was to update some aspects in the readme. We'll fix the build later as immediate priority is live deployment.

**Pull request merged**
